### ISSUE TITLE
diff() from DateTimeInterface not implemented

### ISSUE THREAD

**Issue by kheengz** [cakephp/chronos#155]
on a cakephp 3.5.4 and php 7.1
`diff()` from `DateTimeInterface` not implemented
```php
Fatal error: Class Cake\Chronos\MutableDateTime contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (DateTimeInterface::diff) in /xxx/xxx/vendor/cakephp/chronos/src/MutableDateTime.php on line 51
```

```php
Fatal error: Class Cake\Chronos\MutableDate contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (DateTimeInterface::diff) in /xxx/xxx/vendor/cakephp/chronos/src/MutableDate.php on line 50
```

**Comment by markstory** [comment]
We inherit from `DateTime` which is why we don't explicitly implement that method.

https://github.com/cakephp/chronos/blob/1f3898e49939e2c1801053632f70b6bdfdd9cadd/src/MutableDateTime.php#L51

and 

https://github.com/cakephp/chronos/blob/1f3898e49939e2c1801053632f70b6bdfdd9cadd/src/MutableDate.php#L50

**Comment by kheengz** [comment]
@markstory so what's the way forward same error is persistent with no particular order. it occurs randomly.

**Comment by markstory** [comment]
No idea. What version of PHP7.1 are you on? This sounds very much like #147

**Comment by kheengz** [comment]
@markstory am on **7.1.10**

**Comment by ominfowave** [comment]
if you have xampp stop your service of apache, mysql. Hold sometime, again start the services.
