### ISSUE TITLE
Please add a Changelog.md or similar

### ISSUE THREAD

**Issue by mfn** [cakephp/chronos#183]
It would be nice to have the changelog part of the sources.

When receiving an update via composer, only the actual source files are changed but there's no included description as to why.

The releases on github https://github.com/cakephp/chronos/releases do get proper description, so I think it would great if you would just include them here, too.

Thanks!

**Comment by ravage84** [comment]
If we add a change log file, please let's adhere to https://keepachangelog.com/en/1.0.0/

**Comment by dereuromark** [comment]
A changelog is a bit too static.
Whats wrong with the releases and the changelogs listed in there?
Sure, could be improved a bit more (also in verbosity), but then sure sufficient?

**Comment by dereuromark** [comment]
Not true. 
https://github.com/cakephp/cakephp/releases/tag/3.6.12
All tagged releases can also contain a clean and easy link to the commit log (Changelog us the link here).
That should suffice, pragmatically approaching this.

**Comment by colinodell** [comment]
I think that's a different repository?  The [releases for Chronos](https://github.com/cakephp/chronos/releases) does not have links to the diffs, nor does it (consistently) have things broken down by the type of change.

**Comment by dereuromark** [comment]
Yeah, I am saying it is possible.
The release changelogs here were indeed a bit too rushed and of not so high quality.
Bear in mind that people do all that in their free time, without getting paid for it either.
So we need to find a pragmatic way to automatically do that, and enrich the release changelogs here with sufficient data.

**Comment by ravage84** [comment]
> But adding md files here is not feasible IMO.

Well, I would agree to some extend if you mean "too much additional maintenance work" by "not feasible ", but it is certainly feasible to add a static change log file to a repo. Many project/libraries do so.

**Comment by dereuromark** [comment]
Then you have additional merge conflicts and other issues over time here on meta level.
There is no benefit here for static files, if the process would be correct and properly done already on github release note level. And the github way would be 10x simpler and more feasable to manage over time. Also to fully and properly automate.

**Comment by colinodell** [comment]
If it helps, here's the process we're using in `league/commonmark` and other PHP League projects:

We maintain `CHANGELOG.md` as our primary changelog: https://github.com/thephpleague/commonmark/blob/master/CHANGELOG.md  It follows the Keep A Changelog principles.  Sometimes a maintainer will update it after each PR is merged, but most times we're lazy and only update it right before a release.

Because this file is written in Markdown and Github uses Markdown for release notes, we simply copypaste that one section from the CHANGELOG into the release notes.  No need to rewrite anything!  Compare these two:

 - https://github.com/thephpleague/commonmark/blob/master/CHANGELOG.md#0180---2018-09-18
 - https://github.com/thephpleague/commonmark/releases/tag/0.18.0

So really the only additional maintenance work is running `git commit -m "Update CHANGELOG" && git push origin master`.  We're still writing the same changelogs as before, we just commit them and copypaste them.

As a result, the info can be found in the standard `CHANGELOG` file as well as in Github.  This means that people downloading the package with Composer or cloning the repo with Git have a local copy they can quickly reference.

**Comment by colinodell** [comment]
> Then you have additional merge conflicts and other issues over time here on meta level.

Only have maintainers update this file, just like maintainers only create releases.

> There is no benefit here for static files

The benefit is that the changes are available within the release archive.  No need to fire up the browser, navigate to Github, and look up the changes there.  (Github may be down, the developer may be working offline, etc.)  It makes the DX a little nicer in some cases.

> Also to fully and properly automate.

There are some projects out there which can automate the creation of a changelog! For example: https://github.com/github-changelog-generator/github-changelog-generator  Personally I don't mind taking a few minutes every release, but I completely understand that maintainer time is super valuable, so there's nothing wrong with automation :)

**Comment by ravage84** [comment]
@dereuromark 

> There is no benefit here for static files,

I think this is not true (as @colinodell pointed out) but a oversimplification. Nonethless, I agree with your other statements.

Thank you @colinodell and @mfn for voicing your concerns and ideas.

I'm going to close this now as we are currently discussing this issue iternally in the core dev team.
